### ISSUE TITLE
Document the release cycle, branches

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#75]
It might be nice, as-per @aldaranmoses, to also document a bit how this correlates (roughly or otherwise) to [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), which is a popular workflow, and also see [another resource](https://nvie.com/posts/a-successful-git-branching-model/).

We want to make sure to outline:

* [ ] What is `master` branch
* [ ] What is our early release/testing branch
* [ ] What is our stable release/steam published branch
* [ ] How this correlates to [GitHub Releases][1]
* [ ] Who publishes to Steam
* [ ] How CHANGELOGs are edited/revised

[1]: https://github.com/swlegion/tts/releases
